name: RedCocoa
options:
  bundleIdPrefix: com.redcocoa
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
targets:
  RedCocoa:
    type: application
    platform: iOS
    sources:
      - path: RedCocoa
        excludes:
          - "Info.plist"
          - "WelcomeVideo.mp4"
          - "Fonts"
      # WelcomeVideo.mp4 excluded (large file). Add to RedCocoa/ and run xcodegen to include.
      - path: RedCocoa/Fonts/Inter-Thin.ttf
        type: resource
    settings:
      base:
        INFOPLIST_FILE: RedCocoa/Info.plist
        CODE_SIGN_ENTITLEMENTS: RedCocoa/RedCocoa.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.redcocoa.app
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: Supabase
        product: Supabase
      - sdk: CoreLocation.framework
